# Generated by Django 4.1.7 on 2023-03-06 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0004_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='interested',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
